module SkelBNF where

-- Haskell module generated by the BNF converter

import AbsBNF
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transTreeLex :: TreeLex -> Result
transTreeLex x = case x of
  TreeL integer treelexs -> failure x
  LeafL integer -> failure x

